### ISSUE TITLE
compare_tensors in Getting Started

### ISSUE THREAD

**Issue by akissinger** [Quantomatic/pyzx#57] opened 2020-10-20 14:26 UTC
`Out[8]` in https://github.com/Quantomatic/pyzx/blob/master/demos/gettingstarted.ipynb shows `compare_tensors` returning False, when I think it should be True.

**Comment by jvdwetering** [comment] 2020-10-21 10:12
It returns True for me? The cell looks like this for me:
```
t1 = circ.to_tensor()
t2 = circ2.to_tensor()
# This checks whether t1 and t2 are equal up to some number: t1 == z*t2 for some complex number z
zx.compare_tensors(t1,t2,preserve_scalar=False) 
```
Do you have that as well?

**Comment by jvdwetering** [comment] 2021-01-04 13:10
Is this fine now? Can I close the issue?

**Comment by hmillerbakewell** [comment] 2021-03-09 17:42
I also get "True" on a fresh install of pyzx

**Comment by anitalu724** [comment] 2022-03-21 13:29
My Code:
```
c1 = zx.Circuit.load('Circuits/Fast/tof_3_before')
g1 = c1.to_graph()
g2 = g1.copy()
g2.normalize()
g2 = zx.extract_circuit(g2)
print(zx.compare_tensors(g1.to_tensor(), g2.to_tensor(), preserve_scalar=False))
```

However, the result is **False**. Isn't it weird?

**Comment by jvdwetering** [comment] 2022-03-22 11:19
The problem is that `extract_circuit` expects the diagram to be in graph-like form (only Z-spiders, all spiders fused). If it isn't then its output is just wrong. I thought `extract_circuit` was doing this normalisation step itself, but apparently it doesn't. I can imagine this is quite confusing, so I should probably just add this preprocessing to `extract_circuit`

**Comment by jvdwetering** [comment] 2022-03-22 11:20
Closing this, as you made a new issue #84

**Closed by jvdwetering** 2022-03-22 11:20 UTC
