### ISSUE TITLE
Issues with running the Editor 

### ISSUE THREAD

**Issue by RDPEast** [Quantomatic/pyzx#50] opened 2020-07-30 12:10 UTC
It may be an idea to include the d3 file locally which was the hacky solution I've used.

**Comment by jvdwetering** [comment] 2020-08-01 11:55
Hmm, or I could insert a check to see if the file can be found on the filesystem, and if not it defaults to the online copy.
Or was the problem that even forcing it to use the online copy doesn't work?

**Comment by RDPEast** [comment] 2020-08-01 23:34
So the original problem was with using the online copy. Adding the d3 file locally was my solution to this.

**Comment by jvdwetering** [comment] 2020-08-17 15:01
I still don't understand this bug. Forcing PyZX to use the online copy at https://d3js.org/d3.v5.min.js works fine for me. Which browser are you using, and which version of Jupyter?

**Comment by JoaquinKeller** [comment] 2020-08-24 03:16
Hello, 
I am having a look at pyZX and when following the "getting started" examples zx.draw does nothing. It seems to be a d3js issue. 

How do I "force PyZX to use the online copy at https://d3js.org/d3.v5.min.js" ?

Thanks !

**Comment by jvdwetering** [comment] 2020-08-24 18:56
Go into pyzx/utils.py and comment out the block of lines 95-104 (the try-except block).
What browser are you using?
Seeing as this is a problem for more people I think I'm just gonna bite the bullet and include a copy of d3 with pyzx.

**Comment by JoaquinKeller** [comment] 2020-08-25 03:09
I tried to modify utils.py but it didn't work. (tested with chrome and
firefox)

I've attached the log from the browser console.

There is an "Uncaught ReferenceError: require is not defined" it seems that
the import of d3js didn't succeed...

Maybe a hint here ?
https://stackoverflow.com/questions/19059580/client-on-node-uncaught-referenceerror-require-is-not-defined

**Comment by JoaquinKeller** [comment] 2020-08-25 05:35
I found the bug: It works with "jupyter notebook" it fails with "jupyter
labs"

**Comment by jvdwetering** [comment] 2020-08-26 10:17
Ah yes. It doesn't work me either if I try it with jupyterlab. So it turns out that for jupyterlab you have to manually enable extensions (https://ipywidgets.readthedocs.io/en/latest/user_install.html#installing-the-jupyterlab-extension), which also requires installing node.js. But even after following the instructions I still get the javascript error that 'require' is not defined. I think this has to do with jupyterlab being a bit more strict about how you can execute javascript in a cell. To solve this would require making a separate PyZX extension to jupyterlab, which I am not going to do any time soon.

So my suggestion is to use the classic notebook interface (i.e. in jupyterlab go to Help -> Launch classic notebook)

**Comment by jvdwetering** [comment] 2020-08-26 10:18
@RDPEast were you also using jupyterlab?

**Comment by RDPEast** [comment] 2020-08-26 10:26
No I'm using the notebook, though I still rely on the hard copy of the file. I believe others (i.e Nick) have also encountered problems with just the notebook and downloading the d3 file.

**Comment by jvdwetering** [comment] 2020-08-26 10:32
What does it say in the javascript console when you try it with using the online copy?

**Comment by RDPEast** [comment] 2020-08-26 11:47
Hi John,

So this is a copy and paste from back when it didn't function (I'm loathe to undo the changes I've made to my version of pyzx to double check as it was quite tempermental at first for reasons I still don't understand and I'm rather dependent on the editor at this precise moment) 
![image](https://user-images.githubusercontent.com/13621329/91299621-377eda80-e7a2-11ea-9c1b-c17e332fbb09.png)

**Comment by jvdwetering** [comment] 2020-08-26 12:08
Hmm, I find it interesting that you get a script error before it says "Loading extension: jupyter-js-widgets/extension". That seems to me like an error in your jupyter server, but I really don't understand enough of this to be sure.

**Comment by jvdwetering** [comment] 2021-01-04 13:08
So another thing I encountered that might explain this: If you have a Jupyter notebook with some cells loaded that include javascript, then that javascript remains when you reload the notebook. The way to get it to be "clean" so that it can find the d3 library again is to go Kernel -> Restart and Clear Output.

**Comment by hmillerbakewell** [comment] 2021-02-24 12:41
I found I had the same issue (d3 not loading) and in my case it was caused by `jupyter notebook` not serving files from hidden folders. The command `jupyter notebook --ContentsManager.allow_hidden=True` fixed this issue. It doesn't fix the other issue with `jupyter lab` and `require`, sadly.

**Comment by jvdwetering** [comment] 2022-05-12 16:30
I think the d3 loading issues have now all been fixed, so I'm closing this issue. Please create a new issue if new problems have arisen.

**Closed by jvdwetering** 2022-05-12 16:30 UTC
